### ISSUE TITLE
Variable Rate Limit

### ISSUE THREAD

**Issue by blainesch** [ded/express-limiter#12]
The `lookup` right now is set to an array of values. This is useful, but is always AND not OR. What if I wanted to rate limit by an api key if available and valid, or fallback to an ip? This could potentially use a function instead of an array, that took in the request.

What if falling back to an ip would change how many requests they could make in `total`? I suppose the function above could also pass in the config of the express limiter.

I'd be happy to make a pr once these concepts have been approved.

**Comment by fizerkhan** [comment]
@ded @blainesch it is more important feature because most of developer will use rate limit on API based on API Key. It will be great if you merge the PULL request.

**Comment by wesratcliff** [comment]
Love this feature -- doing some initial testing, it looks like the function assigned to "opts.lookup" is being overwritten with the lookup Array/String.

The first request runs properly but the second attempts to execute the Array as a function.

Could you verify?

This small patch gives the intended behavior:
```
// In application
var options = {
  lookupFn: function(...){},
  ...other options...
}
limiter(options)
```

```
// In express-limiter/index.js
if (typeof(opts.lookupFn) === 'function') {
    middleware = function (middleware, req, res, next) {
        return opts.lookupFn(req, res, opts, function () {
            return middleware(req, res, next)
        })
    }.bind(this, middleware)
}
```
