### ISSUE TITLE
Does "path" field use a regex comparison against incoming requests?

### ISSUE THREAD

**Issue by kentmw** [ded/express-limiter#18]

**Comment by ded** [comment]
it accepts the same arguments that an express route would take, including regular expressions.

also keep in mind though, most "matched"-style routes can use Express' string maters.. eg:

``` js
'/users/:id'
'products/:collection_name/:id'
```

**Comment by kentmw** [comment]
sorry, quick follow up. Anyway to specify if it was a GET/POST?

**Comment by kentmw** [comment]
JK, saw your documentation. thanks
